- .github/workflows/develop_build_deploy.yml
- close #22 
---
- docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/server-spring:${{ needs.build.outputs.sha }}
명령어에서 사용하는 sha 값을 outputs에서 VERSION으로 넘겨주고 있어 에러발생
해당 값 sha로 변경
```
outputs:
sha: ${{ steps.github-sha-short.outputs.sha }}
```
---
- 
--- 
-
> fix: CI/CD outputs 변수명 변경

- src/main/java/com/depromeet/global/error/ErrorResponse.java
- src/main/java/com/depromeet/global/error/exception/CustomException.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- close #8
---
- 에러 응답으로는 1) 상태코드 2) 예외 메세지 3) 발생 시간을 찍어서 반환합니다.
- 예외 응답 시 record를 사용합니다.
---
- 
--- 
-
> feat: 커스텀 예외 및 에러 코드/응답 구현 

- .github/workflows/develop_build_deploy.yml
- .github/workflows/develop_deploy.yml
- Dockerfile
- docker-compose.yaml
- close #15 
---
- 도커 컴포즈 파일을 작성했습니다. 다음과 같이 작동합니다.
- 해당 파일은 프로젝트 루트 디렉토리에 `docker-compose.yaml` 로 관리됩니다.
- deploy 액션이 트리거되면, `scp-action`을 통해 ncp 서버의`home/tenminute`으로 해당 파일을 복사합니다.
- 복사된 컴포즈 파일을 up으로 실행합니다.
- `docker image prune -a -f` 로 사용되지 않는 이미지를 삭제하는 스크립트를 추가했습니다. 
- 빌드 시 `eclipse-temurin` 이미지를 사용하도록 했습니다. 
-  `openjdk` 이미지는 JRE를 제공하지 않기 때문에, 사용하면 안된다고 합니다.
-  aws 서비스를 사용한다면 `amazoncorretto` 를 사용해도 좋지만, 일반적으로는 이클립트 테무린을 권장한다고 합니다. [레퍼런스, 3번 참고](https://www.docker.com/blog/9-tips-for-containerizing-your-spring-boot-code/) 
---
- docker-compose에 `version: "3.8"`
- 2번째 링크에 버전 표 보고 가장 최신 도커 엔진 릴리즈에 대응되는 값을 명시해야 한다고... 
- https://stackoverflow.com/questions/74686606/docker-compose-and-docker-file-versions-differences-and-interferences
- …
> chore: docker compose 적용

- src/main/java/com/depromeet/global/config/response/GlobalResponse.java
- src/main/java/com/depromeet/global/config/response/GlobalResponseAdvice.java
- close #13 
---
- API 성공 응답 시 공통으로 응답 형태를 지정해주도록 어드바이스 생성
- GlabalResponse(record) 생성
- success(boolean), status(int), data(Object), timestamp(LocalDateTime) 필드를 사용합니다.
- 정적 팩토리 of 메소드를 사용하여 객체를 생성합니다 (status, data) 매개변수로 사용
> chore: 성공 응답 공통 처리 어드바이스 생성

- .github/workflows/develop_build_deploy.yml
- settings.gradle
- close #17 
---
- `slack-github-action`을 사용하여 슬랙으로 gradle build scan report의 url을 전송합니다.
(실제로는 \n은 전송되지 않습니다)
- gradle build scan의 report publish를 활성화
- CI 환경에서만 publish 되도록 설정 (`publishAlwaysIf(System.getenv("CI") != null)`) 
---
- 
--- 
-
> chore: Gradle Build Scan 활성화 및 슬랙 전송 워크플로 추가

- .github/workflows/develop_build_deploy.yml
- close #32 
- `github-sha-short` 스텝 이름을 `image-tag` 으로 변경했습니다.
-  곧 deprecated 되는 `set-output` 대신 `GITHUB_OUTPUT` 을 사용하도록 개선했습니다. [(레퍼런스)](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- NCP username을 시크릿 처리했습니다.
- 
-
> chore: 워크플로에서 `set-output` 커맨드 제거

- src/main/java/com/depromeet/global/config/response/GlobalResponseAdvice.java
- close #55 
- `ExampleController에서 `ResponseEntity.ok("test string")` 리턴 시 다음 에러 발생
```
java.lang.ClassCastException: class com.depromeet.global.config.response.GlobalResponse cannot be cast to class java.lang.String (com.depromeet.global.config.response.GlobalResponse is in unnamed module 
```
GlobalResponse 클래스 data 필드가 Object 타입일 때, String 타입으로 객체 전달 시 에러 발생
String은 Object의 하위 클래스이지만 업캐스팅(Upcasting)을 해도 컴파일러가 String을 Object로 암묵적으로 변환하는 것을 허용하지 않는다고 합니다. String이 Object의 서브클래스라 할지라도, 타입 불일치로 처리
> fix: GlobalResponseAdvice 응답 값이 String 타입 예외 처리

- src/main/java/com/depromeet/global/config/response/GlobalResponseAdvice.java
- close #65 
- Swagger는 '/api/v3/api-docs` 로 패칭해서 가져오는데 공통 성공 응답 시 basePackage를 명시해 놓지 않아
스웨거의 응답값 마져 공통으로 응답형식을 바꿔져서 Swagger 해석하지 못하게 되는 문제를 해결합니다.
- GlobalResponseAdvice에 basePackages 적용
- https://devnm.tistory.com/28
> fix: Swagger가 안뜨는 문제 해결

- src/main/java/com/depromeet/global/error/GlobalExceptionHandler.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- close #7 
- GlobalExceptionHandler 생성하였습니다
- 스프링 예외를 미리 처리해둔 ResponseEntityExceptionHandle를 상속 받아 사용합니다
- 기본적인 예외, Custom 예외, 500번대 예외만 잡아두었습니다
- https://github.com/cheese10yun/spring-guide/blob/master/docs/exception-guide.md#%ED%86%B5%EC%9D%BC%EB%90%9C-error-response-%EA%B0%9D%EC%B2%B4
- https://mangkyu.tistory.com/204
> chore: Global Exception Handler 설정

- docker-compose.yaml
- src/main/resources/application-actuator.yml
- src/main/resources/application-datasource.yml
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/test/resources/application-test.yml
- close #52 
- application.yml을 환경변로 분리했습니다.
```yaml
spring:
profiles:
group:
test: "test"
local: "local, datasource"
dev: "dev, datasource, actuator"
prod: "prod, datasource, actuator"
```
기본 `application.yml`파일에서 위와같이 그룹을 통해서 중복 코드를 제거할 수 있습니다.
새로운 환경의 yml파일이 필요하다면 추가해주시면 됩니다.
```yaml
---
spring:
config:
activate:
on-profile: local
---
spring:
config:
activate:
on-profile: dev
```
와 같은 방법은 분리하려했는데 중복코드가 많아서 사용하지 않았습니다
+ 놓친 설정이 있다면 알려주세용 😆
> chore: `application.yml` 환경별 분리

- src/main/java/com/depromeet/global/config/SwaggerConfig.java
- close #67 
- 서버 리스트가 나오지 않는 문제를 해결합니다
- SpringEnvironmentUtil을 사용하여 서버 목록을 동적으로 추가합니다.
- 아래 코드부분은 #69 에서 공통 상수 처리시 변경하겠습니다
```java
private String getServerUrl() {
switch (springEnvironmentUtil.getCurrentProfile()) {
case "prod":
return "https://api.10mm.today";
case "dev":
return "https://dev-api.10mm.today";
default:
return "https://localhost:8080";
}
}
```
> fix: Swagger에 Server 리스트 안보이는 문제해결

- src/test/java/com/depromeet/global/util/MemberUtilTest.java
- close #89
- MemberUtilTest에 DatabaseCleaner가 적용되지 않아
다른 Service 테스트에서 잔여하는 Member로 인해 테스트 실패 케이스 발생
- 
-
> fix: MemberUtilTest에 DatabaseCleaner 적용

- .github/workflows/develop_build_deploy.yml
- .github/workflows/develop_pull_request.yml
- build.gradle
- docker-compose-test.yaml
- src/main/java/com/depromeet/infra/config/RedisConfig.java
- src/main/resources/application-redis.yml
- src/main/resources/application.yml
- src/test/java/com/depromeet/TenminuteApplicationTests.java
- src/test/java/com/depromeet/global/util/MemberUtilTest.java
- src/test/resources/application-test.yml
- close #85
- Redis를 사용하기 위한 Redis Config 추가
- redis yml 파일 생성
- 테스트 환경에서 격리 된 redis를 생성하기위해 `docker-compose-test.yml`을 생성 후 빌드과정에서 사용합니다.
- 기존 `SpringBootTest`에서 미리 생성해 둔 `profile=test`를 사용하고 있지 않아 `@ActiveProfiles`을 통해 test profile을 사용하도록 설정해두었습니다
- 
-
> chore: Redis 설정

- build.gradle
- src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
- src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
- src/main/java/com/depromeet/domain/missionRecord/dto/request/MissionRecordCreateRequest.java
- src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
- close #87 
- 미션 기록 저장 API입니다.
- Validation 의존성 없어서 추가해두었습니다.
- 해당 PR에서는 미션 기록 저장만 존재하고, 이미지와 일지는  #95 이슈 처리 후 작업하도록 하겠습니다.
- 이벤트 발행 및 Redis 관련 처리는 #88 머지 후 작업 예정
- 우선 domain test만 작성해두었습니다 추 후 새로운 이슈에서 Controller, Service 테스트 작성하겠슴니다.
- duration은 분과 초를 나누어서 받도록 프론트 @sumi-0011 와 협의 완료
> feat: 미션 기록 저장 기능 구현

- build.gradle
- src/main/java/com/depromeet/infra/config/properties/PropertiesConfig.java
- src/main/java/com/depromeet/infra/config/redis/RedisConfig.java
- src/main/java/com/depromeet/infra/config/redis/RedisProperties.java
- src/main/java/com/depromeet/infra/config/storage/StorageConfig.java
- src/main/java/com/depromeet/infra/config/storage/StorageProperties.java
- src/main/resources/application-storage.yml
- src/main/resources/application.yml
- src/test/resources/application-test.yml
- close #95 
- NCP Object Storage 설정
- PresignedUrl을 사용하기 위한 설정입니당
- [NCP 오브젝트 스토리지](https://www.ncloud.com/product/storage/objectStorage)는 Amazon S3와 호환되는 API를 제공하여 AWS SDK를 사용합니다
- 설정 정보들을 configuration-processor를 이용하여 추가하고 관리합니다
- storage 환경변수 추가되었습니다 슬랙 서버 채널에 남겨놓았으니 확인 후 추가해주세용
> chore: NCP Object Storage 설정

- src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
- close #91
- 미션 Controller 테스트 코드 구현
- WebMvcTest로 MissionController 테스트만 진행
- AutoConfigureMockMvc로 MockMvc를 자동 구성해주지만, 필터로 자동 구성하지 않도록 했습니다.
- `@MockBean(JpaMetamodelMappingContext.class)` 추가한 이유
- `@WebMvcTest`는 JPA 생성과 관련된 기능이 전혀 존재하지 않는 테스트 어노테이션이여서 JPA Auditing 기능을 사용할 떄`@SpringBootApplication`에 `@EnableJPaAuditing`을 추가하여 사용하고 있기 때문에 발생하는 에러가 발생합니다.
- https://velog.io/@sysy123/Spring-Boot-Error-ControllerTest-Spring-Security-403-%EC%97%90%EB%9F%AC
- https://youtu.be/BZBFw6fBeIU?si=mbXs3VN06SuHw_Qm
- https://velog.io/@suujeen/Error-creating-bean-with-name-jpaAuditingHandler
-
> test: 미션 Controller 테스트 코드 작성

- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
- src/main/java/com/depromeet/domain/mission/service/MissionService.java
- src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepository.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
- src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindResponse.java
- src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/mission/repository/MissionRepositoryTest.java
- close #86 
- 캘린더 뷰에 사용할 미션 내역 리스트 조회 API 개발
- yearMonth로 년월 데이터 받아 처리
- yearMonth를 한 번에 Querydsl로 처리하는 것으로 `year * 100 + month` 추가 연산이 포함되기에 불필요하므로 각각의 and 연산으로 처리
- 미션 내역 리스트 조회 엔드포인트에서 calendar 추가하는 방법은 추후 기획서에서 따로 list content를 받는 영역이 생길 시 `ex) /calendar, /list ` 형식으로 분리하는 방향으로 정의
- 
-
> feat: 미션 내역 리스트 조회

- src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
- src/main/java/com/depromeet/domain/missionRecord/dto/request/MissionRecordCreateRequest.java
- src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindOneResponse.java
- src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- close #110 
- 미션 내역 상세 조회 구현으로 findById로 구현
- 미션 수행한 시간(분)은 duration 값을 toMinutes()로 구현
- 미션 시작한 지 D+Day는 Duration의 between 메서드를 활용해 toDays()로 Day 값 return
- MissionRecordFindOneResponse로 단건 조회에 대한 DTO를 생성했습니다.
- 이전 미션 내역 조회 PR(#107) 에서 미처 구현하지 못한 사항도 수정했습니다
-
> feat: 미션 내역 상세 조회 구현

- src/main/java/com/depromeet/domain/image/api/ImageController.java
- src/main/java/com/depromeet/domain/image/application/ImageService.java
- src/main/java/com/depromeet/domain/image/domain/ImageFileExtension.java
- src/main/java/com/depromeet/domain/image/domain/ImageType.java
- src/main/java/com/depromeet/domain/image/dto/request/MissionRecordImageCreateRequest.java
- src/main/java/com/depromeet/domain/image/dto/request/MissionRecordImageUploadCompleteRequest.java
- src/main/java/com/depromeet/domain/image/dto/response/PresignedUrlResponse.java
- src/main/java/com/depromeet/domain/mission/domain/Mission.java
- src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
- src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/main/java/com/depromeet/infra/config/storage/StorageConfig.java
- src/main/java/com/depromeet/infra/config/storage/StorageProperties.java
- src/main/resources/application-storage.yml
- src/test/java/com/depromeet/domain/image/api/ImageControllerTest.java
- src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
- src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
- close #101 
- StorageConfig에서 기존 AWS SDK를 사용해 PresignedUrlRequest를 만들 때 endpoint가 AWS로 되어있어서 endpoint를 환경변수로 추가하고 NCP endpoint를 넣어주었습니다.
- PresignedUrl 생성 시 ExpireTime을 30초로 설정하였습니다
- 파일 디렉토리는 `/환경(ex:local, dev, prod)/ImageType(ex:mission_record)/{targetId}/image.{imageFileExtension(ex:jpeg, jpg, png)}`와 같습니다. 여기서 targetId는 ImageType에 따라 달라집니다.
(추 후 ImageType에 member_profile, member_background가 추가된다면 targetId는 memberId가 됩니다)
- PresignedUrl 생성 시 해당 미션 기록의 이미지 상태를 `PENDING` 상태로 변경
- PresignedUrl 업로드 완료 처리에서 미션 기록의 업데이트상태를 `COMPLETE`로 변경함과 동시에 미션 일지와 이미지를 업데이트합니다.
> feat: PresignedUrl을 사용하여 이미지 업로드 기능 구현

- src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
- src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordCreateResponse.java
- src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
- src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
- close #129
- 미션 기록 생성 POST /records의 응답 값이 현재 Long으로 되어있는데, 응답 값을 Response 객체로 Wrapping
- 프론트 담당자 @sumi-0011 와 협의 완료
> refactor: 미션 기록 생성 응답 값 response 객체로 Wrapping

- src/main/java/com/depromeet/global/common/constants/UrlConstants.java
- close #137 
- 브라우저 기본 접속 시 www가 추가되어 cors 허용이 안되고 있어 UrlConstants에 www를 추가해주었습니다.
- SERVER_URL은 www가 안붙어서 추가해주지 않았어용
> hotfix: CORS문제로 UrlConstants에 www 추가

- src/main/java/com/depromeet/domain/image/application/ImageService.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordTTLRepository.java
- close #127 
- 이미지 업로드 예외케이스 처리 중 Redis에 TTL이 존재 시 '인증 필요' 대상이므로 이미지 업로드 후 Redis에 저장한 'MissionRecordTTL'을 삭제하여야 합니다.
- MissionRecordTTLRepository에 ID가 Long으로 설정되어있어 String으로 변경하였습니다😥
> feat: 이미지 업로드 예외케이스에서 업로드 완료시 Redis TTL 삭제 기능

- src/main/java/com/depromeet/global/config/swagger/SwaggerConfig.java
- close #146 
- 현재 Swagger에 SecuritySchemes는 accessToken을 넣을 수 있는 Authorization헤더만 존재하는데, refresToken을 넣을 수 있는Refresh-Token헤더 스키마 추가
> feat: Swagger에 RefresgToekn용 SecuritySchemes 추가

- src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- close #121 
- 기획 상 한개의 미션에 미션 기록은 하루에 한개만 가능하여 해당 기능을 추가합니다
- queryDsl에 dayEq 추가하였습니다.
- service 레이어 미션 일지 생성 메서드에서 validate 부분 추가하였습니다
- @sumi-0011와 배포시점 논의 후 협의되면 배포 진행할 예정
> feat: 미션 기록 하루에 한개만 처리 가능하도록 기능 추가

- src/main/java/com/depromeet/global/util/MemberUtil.java
- src/main/java/com/depromeet/global/util/SecurityUtil.java
- src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
- src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
- src/test/java/com/depromeet/global/util/MemberUtilTest.java
- close #147 
- Service 테스트 코드에서 Principal이 null 값인 문제
- principal 객체로 setAuthentication를 하여 설정 후 principal 객체를 읽을 수 있도록 한다.
- 
-
> fix: 유틸리티에서 픽스처 및 Mock 인증 삽입 로직 제거

- src/main/java/com/depromeet/domain/auth/api/AuthController.java
- src/main/java/com/depromeet/domain/auth/application/AuthService.java
- src/main/java/com/depromeet/domain/member/api/MemberController.java
- src/main/java/com/depromeet/domain/member/application/MemberService.java
- src/main/java/com/depromeet/domain/member/domain/Member.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/member/domain/MemberTest.java
- close #154
API 엔드포인트: `/auth/withdrawal`
- 회원탈퇴 로직으로 MemberStatus를 DELETED로 업데이트, redis에 있는 refreshToken 값을 memberId로 삭제
- 추가로 login 시 lastLoginAt, MemberStatus를 Normal로 업데이트
- 
-
> feat: 회원 탈퇴 로직 구현

- docker-compose.yaml
- close #156 
|**서버 인스턴스**|**docker에 올라간 SpringBoot Server**|
|---|---|
|<img src="https://github.com/depromeet/10mm-server/assets/64088250/ed23d1ba-4dd9-4549-8363-20822b47be44" width="600"/>|<img src="https://github.com/depromeet/10mm-server/assets/64088250/41b6fd1e-5f39-4352-a988-e31bf89d1293" width="600"/>|
- 현재 서버 인스턴스는 Asia/Seoul로 설정되어있으나, docker에 띄워진 SpringBoot Server에 TimeZone이 UTC로 되어있어,
Docker environment로 Timezone값을 Asia/Seoul로 설정해주었습니다.
> fix: SpringBoot Server TimeZone Asia/Seoul로 설정

- src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
- close #161 
- `DELETE /records/in-progress` 이미 진행중인 미션 기록들 삭제 API에서 Redis에 있는 MissionRecordTtl은 정상적으로 삭제되나, DB에 저장되어있는 MissionRecord가 삭제되지 않는 이슈가 있습니다.
- MissionRecordRepository가 DI 될 때, MissionRecordRepositoryImple이 주입되어 발생하는 문제였습니다.
- MissionRecordRepositoryImpl에 `deleteByMissionId` 메소드 생성하여 처리
> fix: 진행중인 미션기록 삭제할 때 QueryDsl 메소드 사용하도록 변경

- src/main/java/com/depromeet/domain/image/application/ImageService.java
- src/main/java/com/depromeet/domain/image/dto/request/MemberProfileImageUploadCompleteRequest.java
- close #165 
- 회원 가입 후 이미지가 null 인 상태에서 이미지 변경을 하지 않았을 경우 null로 넘어오기에 nullable 처리합니다.
- 닉네임은 항상 값이 존재해야 하기 때문에 NotNull 추가
> fix: 회원 정보 수정할 때 이미지 nullable 처리

- src/main/java/com/depromeet/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/domain/mission/dto/response/MissionFindAllResponse.java
- src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
- close #167 
- 인증 필요인 미션의 경우 클릭 했을 때 해당 미션을 완료(이미지업로드와 일지작성)하는 화면으로 넘어가는데, 이 때 MissionRecordId도 필요하여 응답객체에 필드 추가
> feat: 미션 목록 조회 시 인증필요인 경우 MissionRecordId도 같이 응답

- src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
- src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
- close #172
- (AS-IS) querydsl 사용한 쿼리로 변경
- (TO-BE) orphanRemoval 사용하도록 변경 (`mission.getMissionRecords().remove(optionalRecord.get());`)
- Mission에서 MissionRecord OneToMany 매핑해두었을 때 CascadeType.ALL로 설정하면 PERSIST할 때 REMOVED된 연관 엔티티를 다시 MANAGED 상태로 변경함
```java
// DefaultPersistEventListender
private void persist(PersistEvent event, PersistContext createCache, Object entity) {
// ...
switch ( entityState( event, entity, entityName, entityEntry ) ) {
case DELETED:
// 엔트리가 DELETED이면 다시 MANAGED로 변경
// -> 연관관계 편의 메서드 or 고아객체 제거 필요
entityEntry.setStatus( Status.MANAGED );
entityEntry.setDeletedState( null );
source.getActionQueue().unScheduleDeletion( entityEntry, event.getObject() );
entityIsDeleted( event, createCache );
break;
```
- https://velog.io/@park2348190/JPA%EC%9D%98-delete-%EC%BF%BC%E …
> refactor: 미션기록 삭제 시 `deleteById` 쿼리가 작동하지 않는 문제 개선

- src/main/java/com/depromeet/domain/auth/api/AuthController.java
- src/main/java/com/depromeet/domain/auth/application/AuthService.java
- src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
- src/main/java/com/depromeet/global/security/JwtAuthenticationFilter.java
- src/main/java/com/depromeet/global/util/CookieUtil.java
- close #171 
- 쿠키 유틸리티 구현
- 토큰 재발급 후 쿠키에 넣도록 세팅
- 기존에 엑세스 토큰, 리프레시 토큰 응답으로 내려주는 API가 이제 쿠키로도 토큰을 내려주도록 함
- `temp-register` 에서 한번 요청 후 재요청 불가하여 토큰 재발급이 불가능한 이슈 수정 -> 첫 회원가입인 경우 저장하고 발급, 아이디 비밀번호 일치하면 저장하지 않고 발급, 아이디 존재하는데 비밀번호 불일치한 예외 발생
- 기존 API와 호환되므로 머지 가능
-
> fix: 토큰 발급 로직 수정 및 발급 토큰을 쿠키로 관리하도록 개선 #171

- .github/workflows/develop_build_deploy.yml
- .github/workflows/production_build_deploy.yml
- .github/workflows/production_deploy.yml
- close #151 
- 프로덕션 환경 배포를 위해 워크플로 작성합니다
> chore: 프로덕션 배포 워크플로 작성

- src/main/java/com/depromeet/domain/member/domain/Profile.java
- src/main/java/com/depromeet/domain/member/dto/response/MemberFindOneResponse.java
- #185 
> CDN 적용 후 속도가 빨라지긴 했으나, 현재 백엔드 이미지 저장 로직에서 같은 파일이름으로 저장되게 되어있는데,
프로필을 변경해도 같은 URL이라 브라우저에서 이미지 캐싱 처리되어 같은 이미지가 문제 존재
- 위와 같은 문제로 브라우저에서 캐싱을 피하기 위해 임시로 timestamp query값 추가
- 이미지 로직 개선 후 제거 예정
> hotfix: 이미지 URL 캐싱 문제로인해 임시로 query 값 추가

- src/main/java/com/depromeet/domain/follow/api/FollowController.java
- src/main/java/com/depromeet/domain/follow/application/FollowService.java
- src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepository.java
- src/main/java/com/depromeet/domain/follow/domain/MemberRelation.java
- src/main/java/com/depromeet/domain/follow/dto/response/FollowFindMeInfoResponse.java
- src/main/java/com/depromeet/domain/follow/dto/response/FollowFindTargetInfoResponse.java
- src/main/java/com/depromeet/domain/follow/dto/response/FollowStatus.java
- src/main/java/com/depromeet/global/error/GlobalExceptionHandler.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/follow/api/FollowControllerTest.java
- src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
- close #192 
- `GET /follows/{targetId}` 타인의 팔로우 카운트 확인
해당 API 응답에는 `팔로잉`, `팔로우`, `맞팔로우`인지 확인해야되기 때문에 response에 FollowStatus를 추가하였습니다.
- `GET /follows/me` 나의 팔로우 카운트 확인
로그인 된 회원 기준으로 카운트 정보를 확인합니다.
- `MemberRelation` Entity에서 follower, following의 단어 혼동이 있어 `source`, `target`으로 변경하였습니다.
- ExceptionHandler에서 `MethodArgumentTypeMismatchException`의 경우 `@PathVariable`에서 binding 실패하였을 경우에도 발생하여 에러메세지와 주석 변경하였습니다.
-
> feat: 나와 타인의 팔로우/팔로잉 카운트 조회

- src/main/java/com/depromeet/domain/member/domain/Profile.java
- close #208 
- 현재 이미지 캐싱을 사용하지 않기 위해 timestamp 값을 직접 추가해주고 있는데, null 인경우에도 timestamp가 붙어서 에러 발생하여 Null 체크 진행
> hotfix: Profile Image가 null 일 때 timestamp 안붙도록 처리

- src/main/java/com/depromeet/domain/mission/api/MissionController.java
- src/main/java/com/depromeet/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/global/util/MemberUtil.java
> fix: request 시 QueryString 아닌 pathVariable targetId로 변경

- src/main/java/com/depromeet/domain/auth/application/AuthService.java
- src/main/java/com/depromeet/domain/auth/domain/OauthProvider.java
- src/main/java/com/depromeet/domain/member/api/MemberController.java
- src/main/java/com/depromeet/domain/member/application/MemberService.java
- src/main/java/com/depromeet/domain/member/domain/OauthInfo.java
- src/main/java/com/depromeet/domain/member/dto/response/MemberSocialInfoResponse.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
- src/test/java/com/depromeet/domain/member/domain/MemberTest.java
- src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
- close #213 
- 멤버 테이블에 oauth_email 필드 추가해서 이메일 정보 저장되도록 함
- id_token에서 이미 이메일 담아 보내주기 때문에 `oidcUser`에서 `getEmail()` 만 해주면 됨
- 소셜 로그인 정보가 아예 없는 경우 jpa가 임베디드 타입을 null로 매핑해주므로, DTO 변환 시 NPE 회피하기 위해 validate 로직 추가해줌
- 일부만 있는 경우 다음과 같이 검증함
- 응답으로 OauthProvider enum을 직접 내려줌 (e.g. `"provider": "KAKAO"`)
- 이때 **멤버 테이블의 oauth_provider에는 id_token의 issuer가 저장**되는데, `of` 로 순회하면서 issuer로 프로바이더 enum을 결정함
- 따라서 각 멤버가 어떤 프로바이더에 해당하는 지 결정할 수 있음
- 테스트 코드 작성함. 테스트 코드 참고하면 로직 이해하는데 도움이 될듯 합니다
- 
-
> feat: 소셜 로그인 정보 조회하기 기능 구현

- src/main/java/com/depromeet/domain/follow/api/FollowController.java
- src/main/java/com/depromeet/domain/follow/application/FollowService.java
- src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepository.java
- src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepositoryCustom.java
- src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepositoryImpl.java
- src/main/java/com/depromeet/domain/follow/dto/response/FollowedMemberResponse.java
- src/main/java/com/depromeet/domain/follow/dto/response/MemberFollowedResponse.java
- src/test/java/com/depromeet/domain/follow/api/FollowControllerTest.java
- src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
- close #198 
|![image](https://github.com/depromeet/10mm-server/assets/64088250/b070f7b6-ed1f-477d-a8f0-0ed77ad60d13)
- 로그인 된 회원 기준 팔로우 한 사람들을 조회
- 이 때, 정렬 조건은 팔로우 목록 중 최신에 미션을 완료한 사람이 있다면 미션 완료한 시간이 최근인 사람 먼저
- 미션을 완료한 사람이 없다면 디폴트 정렬조건으로 팔로우를 한 시간 최신순으로 정렬
> feat: 내가 팔로우 한 사용자들 닉네임,프로필 조회

- .github/workflows/develop_build_deploy.yml
- .github/workflows/production_build_deploy.yml
- docker-compose.yaml
- close #200
- 현재 Build시에 `appleboy/scp-action@v0.1.4`를 사용하여 `docker-compose.yml`을 항시 복사하고 있습니다.
- 해당 step은 `docker-compose.yml`의 변경과 없이 항상 실행되며 약 30s가 걸린다.
- 파일이 업데이트 되었는지 확인이 가능한 [`burnett01/rsync-deployments`](https://github.com/Burnett01/rsync-deployments) 사용
-a: archive
-v: verbose
-z: compress
-r: recursive
--delete: delete files that are not in the source directory
- 약 30s 걸리던 작업 개선 후 약 7s 걸림
- [정상 동작 확인](https://github.com/depromeet/10mm-server/actions/runs/7640375170/job/20815366179)하였습니당
> refactor: Build시 appleboy/scp-action@v0.1.4 속도 개선

- src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepository.java
- src/main/java/com/depromeet/domain/follow/domain/MemberRelation.java
- src/main/java/com/depromeet/domain/member/api/MemberController.java
- src/main/java/com/depromeet/domain/member/application/MemberService.java
- src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
- src/main/java/com/depromeet/domain/member/dto/response/MemberSearchResponse.java
- src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
- close #217 
- 닉네임으로 유저 검색하는 기능을 추가합니다
- 닉네임 검색 시 해당 유저의 프로필 이미지, 닉네임, 팔로우 상태를 응답합니다.
- 검색 정렬조건에 키워드가 일치하는경우 최상단이고 그 이후로는 사전순 입니다.
- 비지니스 로직 테스트코드 작성해놓았으니 참고 부탁드립니당
- 검색 특이 케이스 자음에 받침이 들어간 경우는 형태소 분석이 필요하다고 판단하였고 리소스를 고려하여 우선순위 낮다고 판단
> feat: 닉네임 검색 기능

- src/main/java/com/depromeet/domain/image/application/ImageService.java
- src/main/java/com/depromeet/domain/image/dao/ImageRepository.java
- src/main/java/com/depromeet/domain/image/domain/Image.java
- src/main/java/com/depromeet/domain/member/domain/Profile.java
- src/main/java/com/depromeet/global/common/constants/UrlConstants.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
- close #185 
- Image Key를 담을 Image Domain을 생성하였습니다.
- 이미지 업로드 시 UUID를 통해 이미지 키를 생성하고 저장합니다.
- 이미지 업로드 처리 완료시에 이미지 키를 조회하고 해당 이미지 키 값을 사용하여 ImageUrl을 설정합니다.
- ImageUrl을 설정하는 부분에서 CDN 주소를 사용하도록 추가하였습니다.
- 테스트코드에 파일명 이스케이프 처리하였습니다.
> refactor: Image 업로드 시 ImageKey 관리

- src/main/java/com/depromeet/domain/image/domain/ImageFileExtension.java
- src/main/java/com/depromeet/domain/member/application/MemberService.java
- src/main/java/com/depromeet/domain/member/dto/response/MemberFindOneResponse.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- close #228 
- 프론트 요청으로 인해 `ImageFileExtension`을 응답하도록 추가합니다.
- `ImageFileExtension`을 응답하는 이유는 현재 이미지 변경과 닉네임 변경이 통합되어있어, 추 후 이를 분리하고 제거 할 예정
> hotfix: 회원 정보 조회 시 ImageFileExtension도 같이 응답하도록 수정

- src/main/java/com/depromeet/domain/image/application/ImageService.java
- close #232
- 회원 PresignedUrl 발급 시 이미지 키를 저장하지 않아서 회원 프로필 이미지 수정되지 않는 문제를 해결
> hotfix: 회원 프로필 이미지 변경 PresignedUrl 발급 시 이미지 키 생성

- src/main/java/com/depromeet/domain/auth/api/AuthController.java
- src/main/java/com/depromeet/domain/auth/application/AuthService.java
- src/main/java/com/depromeet/domain/auth/dto/response/SocialLoginResponse.java
- src/main/java/com/depromeet/domain/member/domain/Member.java
- src/main/java/com/depromeet/domain/member/domain/MemberRole.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/main/java/com/depromeet/global/security/CustomOidcUser.java
- src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
- src/test/java/com/depromeet/domain/member/domain/MemberTest.java
- src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
- src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
- src/test/java/com/depromeet/global/util/MemberUtilTest.java
- close #230
- `MemberRole` 에서 `GUEST` 상태를 제거했습니다.
- 닉네임 변경 및 GUEST -> USER 상태로 업데이트하는 `register()` 관련 메서드를 제거했습니다.
- ID/PW 관련 메서드를 삭제했습니다. (`createGuestMember(String username, String password)`)
- ID/PW 관련 컨트롤러 / 서비스 메서드를 deprecated 처리했습니다.
- 게스트 관련 로직의 경우 아무런 동작을 하지 않도록 수정했습니다 (`// do nothing` 주석 참고)
- 소셜 로그인 response의 `isGuest` 필드는 항상 false를 리턴합니다.
- 현재 테스트 시 `createNormalMember(Profile profile)` 을 사용하고 있는데, 테스트 전용 생성자를 사용하는 것은 지양해야 하므로 `createNormalMember(OauthInfo info, String nickname)` 으로 대체해야 합니다.
- 이에 따라 `createNormalMember(Profile profile)` 을 deprecated 처리했습니다.
-
> feat: 랜덤 닉네임 기능 도입에 따른 `GUEST` 상태 제거

- src/main/java/com/depromeet/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
- src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
- src/test/java/com/depromeet/domain/mission/repository/MissionRepositoryTest.java
> fix: 미션 리스트 조회 시 InProgress인 미션만 조회로 변경

- src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
- src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordCalendarResponse.java
- src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindOneResponse.java
- src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindResponse.java
- close #250 
- 기존 미션기록 조회 시 n일차에 해당하는 값을 계산해서 보내주고 있었는데, 기획 상 미션 기록을 완료하지 않은 날(empty case)일 때도 n일차에 해당하는 값을 보어주여야 합니다. (이미지 맨 우측 화면 참고)
- 따라서 `GET /records - 미션 기록 조회(캘린더뷰) API`에서 미션의 시작 시간과 끝 시간을 추가
(프론트와 협의 완료 @wade3420)
> feat: 캘린더 뷰 조회 응답에 미션 시작 시간, 끝 시간을 추가

- src/main/java/com/depromeet/domain/member/application/MemberService.java
- src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
- close #253 
- 당근조이와 도모는 현재 맞팔로우 상태인데, 당근조이만 도모를 팔로우한 경우처럼 `맞팔로우`버튼이 보이는 문제 발생
- 로직 상 잘못 코드 짜놨더라구용 급하게 수정했슴니돠😥
> fix: 닉네임 조회 시 팔로우 상태 버그 수정

- src/main/java/com/depromeet/domain/image/api/ImageController.java
- src/main/java/com/depromeet/domain/image/application/ImageService.java
- src/main/java/com/depromeet/domain/image/dto/request/MemberProfileImageUploadCompleteRequest.java
- src/main/java/com/depromeet/domain/member/api/MemberController.java
- src/main/java/com/depromeet/domain/member/application/MemberService.java
- src/main/java/com/depromeet/domain/member/domain/Member.java
- src/main/java/com/depromeet/domain/member/dto/request/NicknameUpdateRequest.java
- src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
- close #255
- `upload-complete/v2` 를 구현했습니다.
- 기존과 동일하게 동작하되, nickname 필드를 전달하지 않아야 합니다.
- 만약 전달하더라도, 내부적으로는 아무런 동작을 하지 않습니다 (기존 닉네임 유지)
- 닉네임을 전달할 수 있는 이유는 v1과 동일한 DTO를 사용하기 때문입니다. -> 해당 DTO에서 nickname not null 검증 조건을 제거했습니다.
- 닉네임 중복검증 메서드를 재사용을 위해 분리했습니다.
- 닉네임 변경 API를 구현했습니다. (`PUT members/me/nickname`)
- 닉네임 변경 테스트를 작성했습니다.
- 
-
> refactor: 닉네임 및 프로필 이미지 API를 각각의 V2 API로 분리

- .github/workflows/develop_build_deploy.yml
- src/main/java/com/depromeet/global/config/swagger/SwaggerConfig.java
- src/main/java/com/depromeet/global/security/JwtAuthenticationFilter.java
- src/main/java/com/depromeet/global/util/SecurityUtil.java
- close #258
- close #240 
- 스웨거 시큐리티 스키마 활성화 처리해서 API 요청 날릴 떄 헤더 포함되도록 세팅했습니다.
- 헤더 가져와서 Bearer prefix 떼주는 부분에서 NPE 발생하는 이슈 있어서, Optional로 감싸줬습니다.
- p.s. 오늘 서버에서 503 터지는 이슈 있어서 서버 로그 확인해보니 누군가 NPE를 마구마구 터트리고 있어서... 서버가 공격당하는 줄 알고 식겁했지만... 알고보니 헬스체크를 정기적으로 날리는 LB였고... 헬스체크 API에서 NPE가 터지고 있어서 해당 이슈가 발생하는 거였습니다...
- 시큐리티 유틸리티에서 익명 유저로 로그인하는 경우 `getName()` 호출할 때 memberId가 아니라 문자열이 들어오기 때문에, try-catch로 감싸줬습니다.
- 또한 시큐리티 유틸에서 `PrincipalDetails` 로 캐스팅하는 방법 대신 `Authentication` 인터페이스가 제공하는 `getName()` 사용해서 좀 더 우아하게 처리해줬습니다.
- 
-
> fix: 쿠키 적용 후 개발서버에서 에러 발생하는 문제 해결

- src/main/java/com/depromeet/domain/member/api/MemberController.java
- src/main/java/com/depromeet/domain/member/application/MemberService.java
- src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
- src/main/java/com/depromeet/domain/member/domain/Profile.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
- close #266 
**nickname 검색 시 특수문자, 공백에 대한 예외처리**
- 정규식으로 한글, 숫자, 영문 대소문자는 `_`로 replaceAll 처리 후 nativeQuery에서 _로 escaping
- controller에서는 `%` 키워드가 직접 들어올 시 null로 처리하게 되어 NullPointException이 터지는 이슈 해결
- 디쟌팀과 추가 기획사항이 발생 시 추가 수정 예정
- 이렇게 하는 게 맞는 지 본인도 헷갈리니 꼼꼼한 리뷰 바람
> fix: nickname 검색 예외 처리 (escape)

- src/main/java/com/depromeet/domain/follow/api/FollowController.java
- src/main/java/com/depromeet/domain/follow/application/FollowService.java
- src/main/java/com/depromeet/domain/follow/dto/response/FollowListResponse.java
- close #273 
- 회원 프로필 페이지에서 팔로잉/팔로워 카운트는 현재 보여주고 있으나, 클릭 시(위 이미지 우측) 리스트를 조회할 수 있어야 합니다.
아래와 같이 API 응답 예정입니다
```java
{
"success": true,
"status": 200,
"data": {
"targetNickname": "",
"followingList": [
{
"memberId": 2,
"nickname": "ㅅㄷㄴㅅ",
"profileImageUrl": "https://kr.object.ncloudstorage.com/10mm-images/local/member_profile/1/image.jpeg",
"followStatus": "FOLLOWING"
},
{
"memberId": 4,
"nickname": "4번",
"profileImageUrl": "https://kr.object.ncloudstorage.com/10mm-images/local/member_profile/1/image.jpeg",
"followStatus": "FOLLOWING"
}
],
"followerList": [
{
"memberId": 5,
"nickname": "5",
"profileImageUrl": "https://kr.object.ncloudstorage.com/10mm-images/local/member_profile/1/image.jpeg",
"followStatus": "FOLLOWED_BY_ME"
}
]
},
"timestamp": "2024-02-05T12:51:27.056682"
}
```
> feat: 유저 팔로잉/팔로워 목록 조회 API

- src/main/java/com/depromeet/domain/follow/api/FollowController.java
- src/main/java/com/depromeet/domain/member/domain/FcmInfo.java
- src/main/java/com/depromeet/domain/member/domain/Member.java
- src/main/java/com/depromeet/global/config/fcm/FcmService.java
- close #278
- 현재 fcm 토큰 값이 null이거나, 다른 공백 값으로 채웠을 때 푸시알림을 보낸다면 아래와 같은 에러 발생
`Exactly one of token, topic or condition must be specified`
- 토큰이 빈값일 때 보내지 않도록 설정
> fix: fcm 토큰이 빈 값이라면 푸시 알림을 보내지 않도록 설정

- src/main/java/com/depromeet/domain/auth/application/AuthService.java
- src/main/java/com/depromeet/domain/member/api/MemberController.java
- src/main/java/com/depromeet/domain/member/application/MemberService.java
- src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
- src/main/java/com/depromeet/global/util/CookieUtil.java
- close #269 
- 기존에 nickname을 사용하고 있는 로직으로 인해 회원탈퇴가 작동하지 않는 이슈를 해결했습니다.
- 회원 탈퇴 시 `OAuthInfo` 를 삭제하는 대신 해당 정보를 유지하고 회원탈퇴한 경우에는 재가입이 가능하도록 변경했습니다.
- 쿠키 유틸리티에 쿠키 삭제 로직을 구현했습니다.
- 프론트가 회원탈퇴 시 `UsernameCheckRequest` 을 보내지 않도록 수정해야 합니다. 단, 수정하지 않더라도 기능은 작동합니다.
-
> feat: 소셜 로그인 회원탈퇴 기능 구현

- src/main/java/com/depromeet/domain/feed/api/FeedController.java
- src/main/java/com/depromeet/domain/feed/application/FeedService.java
- src/main/java/com/depromeet/domain/feed/dto/response/FeedOneByProfileResponse.java
- src/main/java/com/depromeet/domain/feed/dto/response/FeedOneResponse.java
- src/main/java/com/depromeet/domain/follow/application/FollowService.java
- src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepositoryImpl.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
- src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
- src/main/resources/application-local.yml
- close #270 
- 피드 탭 구현 사항으로 엔드포인트는 `/feed/me`, `/feed/{targerId}`로 구현
- `/feed/me`는 탭에 있는 feed 버튼을 클릭 시 동작되는 API
- member, mission, missionRecord를 join해서 필요한 필드에 대해서만 select하는 방식이기에 Projections 생성자 방식을 사용
- 피드같은 경우 미션 내역이 빠르게 증가되어 Latency를 고려하여 100개까지 LIMIT 제한
- Projections를 사용을 위한 데이터 모델은 FeedOneResponse로 DTO record 구현
- Projections를 사용하기에 fetchJoin이 아닌 on절을 사용한 매핑
- `/feed/{targerId}`는 마이프로필과 타인 프로필에 보여지는 피드 API
- targerId가 본인인 경우 공개 여부 상관없이 전부 조회하고, 아닌 경우 팔로잉 관계에 따라 공개 여부를 결정하여 조회해 response
- `/feed/me` API 호출 시 위와 같은 쿼리가 한번 더 발생되는 현상이 있어 같이 고민하면 좋을 듯합니다.
-
> feat: 피드 탭 구현

- src/main/java/com/depromeet/domain/follow/application/FollowService.java
- close #288 
- 현재 푸시 알림 전송 시 팔로우를 한 회원의 닉네임이 null로 나옵니다.
- profile에 존재하는 nickname을 넣어줘야하는데, SNS 로그인 전 아이디/비밀번호 로그인의 username을 넣어주고있음
- nickname을 넣어주도록 변경
> hotfix: 푸시 알림 시 닉네임이 username이 아닌 nickname을 사용하도록 변경(main)

- src/main/java/com/depromeet/domain/follow/application/FollowService.java
- close #288 
- 현재 푸시 알림 전송 시 팔로우를 한 회원의 닉네임이 null로 나옵니다.
- profile에 존재하는 nickname을 넣어줘야하는데, SNS 로그인 전 아이디/비밀번호 로그인의 username을 넣어주고있음
- nickname을 넣어주도록 변경
> hotfix: 푸시 알림 시 닉네임이 username이 아닌 nickname을 사용하도록 변경(develop)

- src/main/java/com/depromeet/global/common/constants/UrlConstants.java
- src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
- close #291
- CORS 설정에 `*.ngrok-free.app` 오리진 패턴 추가
- 프론트 로컬 https 접속을 위해 `https://localhost:3000` 오리진 패턴 추가
- 
-
> fix: 모바일 개발환경 테스트를 위해 CORS 정책에 ngrok 도메인 추가

- src/main/java/com/depromeet/domain/follow/api/FollowController.java
- src/main/java/com/depromeet/domain/follow/application/FollowService.java
- src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
- close #295
- 현재 닉네임 검색과 같은 곳에서 팔로우를 취소했을 떄 상대방이 나를 팔로우 하고 있는지 아닌지에 따라 버튼이 `팔로우` / `맞팔로우`로 달라져야 한다 .
- 프론트 닉네임 검색(리스트 뷰)에서 리패칭을 한다면 순서가 달라진다거나 하는 이슈가 있어 팔로우 취소 API 에서 응답
> feat: 팔로우 취소 시 상대의 팔로우 상태 응답하도록 변경

- src/main/java/com/depromeet/domain/mission/dto/response/MissionFindResponse.java
- src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
- close #303 
- 종료 미션 페이지 개발 중 해당 미션이 언제부터 언제 끝났는지 기간을 넣어줘야하는데 현재 미션 조회에서는 응답 값에 시작시간과 끝나는 시간이 존재하지 않아서 추가
(@sumi-0011 님 요청)
- 미션 단건조회 테스트 코드 변경
> feat: 미션 단건조회 응답 값에 미션 시작시간과 끝나는 시간 추가

- src/main/java/com/depromeet/domain/feed/dto/response/FeedOneByProfileResponse.java
- close #307 
- 피드 API에서 `FeedOneByProfileResponse`로 return 해주고 있는데, 미션 시작한지 N일차(sinceDay) 값 계산을 mission이 아닌 missionRecord로 계산하고있어 이를 수정합니다.
`FeedOneByProfileResponse.java`
**AS-IS**
```java
public static FeedOneByProfileResponse of(MissionRecord record) {
return new FeedOneByProfileResponse(
record.getMission().getId(),
record.getId(),
record.getMission().getName(),
record.getImageUrl(),
record.getDuration().toMinutes(),
Duration.between(record.getStartedAt(), LocalDateTime.now()).toDays() + 1,
record.getStartedAt(),
record.getFinishedAt());
}
```
**TO-BE**
```java
public static FeedOneByProfileResponse of(MissionRecord record) {
return new FeedOneByProfileResponse(
record.getMission().getId(),
record.getId(),
record.getMission().getName(),
record.getImageUrl(), …
```
> hotfix: 피드 Response에 미션 시작한지 N일차(sinceDay) 데이터 값이 올바르게 나오지 않는 버그

- src/main/java/com/depromeet/domain/follow/application/FollowService.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
- close #318 
- 현재 프론트에서 접근 할 수 있는 페이지는 없긴 하지만, 로직 상 본인이 본인을 팔로우하는 경우 예외처리를 해주고 있지 않아 본인이 본인팔로우 한 DEV DB에 데이터 존재하여 이를 예외처리 합니다
> fix: 본인이 본인을 팔로우하는 경우 Validation 추가

- src/main/java/com/depromeet/domain/mission/api/MissionController.java
- src/main/java/com/depromeet/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
- src/main/java/com/depromeet/domain/mission/domain/Mission.java
- src/main/java/com/depromeet/domain/mission/dto/response/MissionSummaryItem.java
- src/main/java/com/depromeet/domain/mission/dto/response/MissionSummaryListResponse.java
- close #305
- 날짜를 선택했을 때 해당 날짜에 미션 리스트와 미션을 완수하였는지 안하였는지 확인 할 수 있어야 합니다.
- 정렬 조건은 완료한 미션 먼저오고 미완료 미션은 후에 오고, 같은 순서일때는 먼저 종료된 미션이 나중에 와야합니다.(아래 이미지 참고)
> feat: 미션 전체 현황 - 날짜로 미션 목록 조회

- src/main/java/com/depromeet/domain/mission/application/MissionService.java
- close #323
- 입력 받은 날짜에 해당하는 기록이 존재하는지 여부를 체크해야하는데 체크하고 있지 않는 문제를 해결
> hotfix: 통계 미션 목록 조회 날짜 비교 추가

- src/main/java/com/depromeet/domain/notification/domain/NotificationType.java
- src/main/java/com/depromeet/domain/reaction/application/ReactionService.java
- src/main/java/com/depromeet/global/common/constants/PushNotificationConstants.java
- close #329 
- 리액션을 추가할 때 해당 미션을 올린 사용자에게 푸시메세지를 발송합니다
- notifiaction 작업 시 이상하게 리액션 조회 Test만 깨지더라구요,,
- notification 쪽은 @woobottle 과 추 후 data에 id값 보내주는 작업해야하는데 그 때 같이 작업하도록 하겠습니다
> feat: 리액션 추가 시 푸시 메세지 발송

- src/main/java/com/depromeet/domain/mission/domain/Mission.java
- src/main/java/com/depromeet/domain/notification/application/PushService.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/notification/application/PushServiceTest.java
- close #325 
- #322 해당 이슈에서 친구 목록에서 종료미션은 보이지 않도록 처리되어있어 문제되진 않지만,
- 종료미션일 경우 재촉하기가 불가능하도록 검증 추가 예정
> fix: 종료미션의 경우 재촉하기 불가능하도록 검증 추가

- src/main/java/com/depromeet/domain/mission/application/MissionService.java
- close #343
- 현재 REQUIRED일때만 missionRecordId를 넘겨주는데, 미션 목록에서 리액션을 같이 조회해야하고, 리액션은 missionRecordId를 통해서 조회하기 때문에 해당 필드에 값이 추가되어야 합니다
> feat: 미션 기록 조회 시 COMPLETE 일때 missionRecordId 추가

- src/main/java/com/depromeet/domain/feed/dto/response/FeedOneByProfileResponse.java
- src/main/java/com/depromeet/domain/feed/dto/response/FeedOneResponse.java
- src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindOneResponse.java
- src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
- close #348
- 미션 기록에서 미션 시작일 기점으로 N일에 해당하는 날짜에 미션을 완료하였을시 정상적으로 N일이 표시되어야 하지만, 표시되고 있지 않습니다.
- `2024.02.18`에 '등교'라는 미션이 생성되었고, `2024.02.18`에 완료한 기록은 1일차, `2024.02.19`에 완료한 기록은 2일차로 표기되어야 하지만 모두 1일차로 나오고 있습니다.
|1일차에 해당하여 정상|2일차로 표기되어야 하지만 1일차로 표기|피드 뷰에서도 동일한 이슈 존재|
|--|--|--|
|![image](https://github.com/depromeet/10mm-server/assets/64088250/bf5819a9-fdc9-4f7f-a0e6-d0e5f46c209e)|![image](https://github.com/depromeet/10mm-server/assets/64088250/9dcbd3cb-6a86-4beb-a21c-baaf0fa1969d)|![image](https://github.com/depromeet/10mm-server/assets/64088250/b576c637-9699-4e98-aeb8-6754c82a000c)|
- sinceDay의 기존 계산 로직은 LocalDateTime으로 24시간 이상 차이나게 되면, 예상 값보다 +1 되는 문제가 존재합니다.
- 시간과 관계 없이 해당 날짜로만 계산하기 위해 `ChronoUnit.DAYS.between`을 통해 계산하였습니다.
- `sinceDay`를 구하는 곳 모두 변경하였습니다 (피드 탭, 전체 탭, 미션 기록 상세조회)
> fix: sinceDay 계산 로직 변경

- src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
- src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
- close #356
- 미션기록에 리액션 컬렉션 추가했습니다.
- cascade remove 걸어서 미션기록 제거 시 자동으로 연관된 리액션 제거되도록 했습니다.
- 관련하여 테스트 코드 작성해두었습니다.
- 피드와 통합하는 이슈는 생각보다 문제가 많아서 별도 이슈로 작업하겠습니다
- 
-
> fix: 미션 기록 삭제가 안되는 문제

- src/main/java/com/depromeet/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepository.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
- src/main/java/com/depromeet/domain/mission/domain/Mission.java
- src/main/java/com/depromeet/domain/mission/dto/request/MissionCreateRequest.java
- src/main/java/com/depromeet/domain/mission/dto/request/MissionUpdateRequest.java
- src/main/java/com/depromeet/domain/mission/dto/response/MissionRemindPushResponse.java
- src/main/java/com/depromeet/global/common/constants/PushNotificationConstants.java
- src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
- src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
- src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
- src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
- src/test/java/com/depromeet/domain/mission/domain/MissionTest.java
- src/test/java/com/depromeet/domain/mission/repository/MissionRepositoryTest.java
- src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
- src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
- src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
- src/test/java/com/depromeet/domain/notification/application/PushServiceTest.java
- src/test/java/com/depromeet/domain/reaction/application/ReactionServiceTest.java
- close #363 
- 미션 시작 리마인드 알림시간 설정을 위한 mission 엔티티에 remindedTime(nullable) 추가
- 생성, 수정 시 remindedTime LocalTime 필드 추가 Request하도록 구현
- Scheduler에서 매 10분마다 In-progress인 미션 대상으로 전체 조회
- 조회 후 현재 now의 LocalTime과 설정한 미션 리마인드 시간 LocalTime과 동일한 지 체크
- 체크 후 대상 미션에 대하여 fcmToken을 each로 {미션명}을 파라미터로 받아 적합하게 조합한 푸시 알림 전송
- 
-
> feat: 미션 리마인드 알림 시간 설정 및 시간에 따른 푸시 알림 전송

- src/main/java/com/depromeet/domain/auth/application/AuthService.java
- src/main/java/com/depromeet/domain/auth/domain/LandingStatus.java
- src/main/java/com/depromeet/domain/auth/dto/response/SocialLoginResponse.java
- close #372
- 어지간하면 `Member` 도메인 내부 상태로 `LandingStatus` 를 결정할 수 있으면 더 깔끔한 로직이 나왔을텐데 (`LandingStatus.of(member)`) 같은 식으로요) 뭔가... 뭔가 아쉽네요
- 일단 서비스 단에서 결정하는 것으로 해두었습니다. 
- 랜딩 상태를 결정하려면 멤버의 존재 여부가 필요한데, 이 부분은 `fetchOrCreate` 의 내부 로직에서 쓰고 있어서 `fetchOrCreate` 를 제거하고 대신 `findByOidcUser` 를 사용하여 서비스 메서드 전체 컨텍스트에서 존재 여부를 참조할 수 있도록 구현했습니다.
- 
-
> feat: 소셜 로그인 후 랜딩 상태 결정하는 기능 구현

- src/main/java/com/depromeet/domain/comment/api/CommentController.java
- src/main/java/com/depromeet/domain/comment/application/CommentService.java
- src/main/java/com/depromeet/domain/comment/dao/CommentRepository.java
- src/main/java/com/depromeet/domain/comment/domain/Comment.java
- src/main/java/com/depromeet/domain/comment/dto/CommentDto.java
- src/main/java/com/depromeet/domain/comment/dto/request/CommentCreateRequest.java
- src/main/java/com/depromeet/domain/comment/dto/request/CommentUpdateRequest.java
- src/main/java/com/depromeet/domain/comment/dto/response/CommentDto.java
- src/main/java/com/depromeet/domain/feed/application/FeedService.java
- src/main/java/com/depromeet/domain/feed/dto/response/FeedOneByProfileResponse.java
- src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/comment/application/CommentServiceTest.java
- close #366
- 리액션 기능과 전반적으로 비슷합니다만 조회는 #359 에서 작업하기 위해 제외했습니다.
- 생성 / 수정 DTO 굳이 다르게 둘 필요가 없을 것 같다는 생각이 들어서 공통으로 쓸 `CommentDto` 응답 DTO를 만들었습니다. 확실히 좋네요. 
- 각종 정책 검증하기 위한 테스트 코드를 작성했습니다.
- 
-
> feat: 댓글 생성, 수정, 삭제 기능

- src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
- close #379 
- 인증 했을때 시작 시간이랑 종료 시간이랑 24시간 비교하는 로직 추가
- 
-
> 🐛 12시 이후 미션 인증 안되는 에러 처리

- src/main/java/com/depromeet/domain/member/dao/MemberRepositoryImpl.java
- src/main/java/com/depromeet/domain/mission/application/MissionService.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepository.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
- src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
- src/main/java/com/depromeet/global/common/constants/PushNotificationConstants.java
- src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
- close #381 
- 리마인드 알림 조회 쿼리 시 필요한 조건처리 기존 `@EntityGraph`를 지우고 Querydsl로 전환하여 조건처리
- 미션을 완료했는지 안했는 지 여부 판단 조건이 필요
- 알림 메세지 내용(body) 변경
- 22시 리마인드 알림, 미션 진행중인지에 대한 where절 하나 추가 (findMissionNonCompletedMembers 메서드)
-
> fix: 리마인드 푸시 알림할 미션 대상 조건 처리

- src/main/java/com/depromeet/global/util/CookieUtil.java
- src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
- close #385 
- 테스트 코드는 databaseCleaner 를 사용하고 있는데, `@Transactional` 유일하게 하나 남아있어서 삭제 및 테스트 수정
- 잠수함 패치로 CookieUtil에서 ResponseCookie httpOnly 옵션 true 변경
-
> test: missionService 테스트 코드 Transactional 삭제

- src/main/java/com/depromeet/domain/notification/api/NotificationController.java
- src/main/java/com/depromeet/domain/notification/application/NotificationService.java
- src/main/java/com/depromeet/domain/notification/dao/NotificationRepository.java
- src/main/java/com/depromeet/domain/notification/dto/NotificationFindAllResponse.java
- src/test/java/com/depromeet/domain/notification/application/NotificationServiceTest.java
- close #365 
- push 패키지를 notification으로 변경하였습니다.
- 로그인 된 유저의 모든 알림 내역을 조회합니다 
- notification쪽 로직 이벤트로 분리하면 좋겠네용
> feat: 알림을 확인 할 수 있는 알림센터 기능 추가

- .github/workflows/production_build_deploy.yml
> hotfix: 도커 이미지를 arm64 플랫폼으로 빌드하도록 수정

- src/test/java/com/depromeet/DatabaseCleaner.java
- src/test/java/com/depromeet/NoTransactionExtension.java
- src/test/java/com/depromeet/domain/comment/application/CommentServiceTest.java
- src/test/java/com/depromeet/domain/feed/application/FeedServiceTest.java
- src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
- src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
- src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
- src/test/java/com/depromeet/domain/mission/repository/MissionRepositoryTest.java
- src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
- src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
- src/test/java/com/depromeet/domain/notification/application/NotificationServiceTest.java
- src/test/java/com/depromeet/domain/notification/application/PushServiceTest.java
- src/test/java/com/depromeet/domain/ranking/application/RankingServiceTest.java
- src/test/java/com/depromeet/domain/reaction/application/ReactionServiceTest.java
- src/test/java/com/depromeet/global/util/MemberUtilTest.java
- src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
- src/test/resources/junit-platform.properties
- close #388 
- JUnit의 Extension 활용
- Auto Detection
- [@Transactional 없애려다 오픈소스 라이브러리까지 만든 이야기](https://blog.ban-life.com/transactional-%EC%97%86%EC%95%A0%EB%A0%A4%EB%8B%A4-%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC%EA%B9%8C%EC%A7%80-%EB%A7%8C%EB%93%A0-%EC%9D%B4%EC%95%BC%EA%B8%B0-5426116036bb)
- [JUnit 5 extension](https://www.baeldung.com/junit-5-extensions)
-
> test: Database cleaner 리팩토링

- src/main/java/com/depromeet/domain/follow/application/FollowService.java
- src/main/java/com/depromeet/domain/notification/application/NotificationService.java
- src/main/java/com/depromeet/domain/notification/domain/Notification.java
- src/main/java/com/depromeet/domain/notification/dto/NotificationFindAllResponse.java
- src/main/java/com/depromeet/global/error/exception/ErrorCode.java
- close #409 
- 기존 생성해두었던 notification 테이블의 경우 로그 형태로 값을 저장하고있어
딥링크처리하였을 때 이동 대상이 없어 테이블 컬럼을 추가하였습니다.
- 우병좌 요청으로 메세지 추가하도록 메소드 생성하였습니다.
- 현재 팔로우의 경우 알림센터의 적재하고 있지 않는데 이부분 추가 이슈에서 작업하겠습니당
-
> feat: 알림센터 Message추가와 클릭 시 대상으로 이동할 수 있도록 자원 ID와 추가

- build.gradle
- scripts/pre-commit
- src/main/java/com/depromeet/scheduler/member/MemberBatchScheduler.java
- close #411 
- 기존 pre-commit은 spotless를 check만 진행
- 수정된 pre-commit은 spotlessApply하도록 진행
- 적용 후 gradle에서 updateGitHooks 실행할 것
- 그래도 안된다면 .git/hooks 에서 pre-commit 지우고 실행해볼 것
-
> chore: pre-commit 시 spotlessApply 실행

- build.gradle
- src/main/java/com/depromeet/domain/notification/domain/Notification.java
- src/main/java/com/depromeet/domain/ranking/dao/RankingRepository.java
- src/main/resources/application-datasource.yml
- src/test/java/com/depromeet/DatabaseCleaner.java
- src/test/java/com/depromeet/domain/ranking/application/RankingServiceTest.java
- src/test/resources/application-test.yml
- close #427
- rds 대신 supabase free tier를 사용하기로 결정했습니다.
- 이에 맞춰 mysql -> postgresql 데이터 마이그레이션 및 코드베이스 수정 진행했습니다.
- 데이터 마이그레이션의 경우 hibernate가 postgresql에서 ddl-auto로 만들어주는 스키마에 맞춰서 넣어줬습니다.
- 이때 자잘하게 맞춰줘야 되는 부분이 있었는데 자세한 건 아래서 설명드리겠습니다.
- postgresql에서 알림 엔티티가 source_id 및 target_id에 대하여 unique 제약조건을 추가하는 문제가 있었습니다 (mysql에서는 해당 제약조건 없었음)
- postgresql에서는 onetoone을 '원래 엔티티에 대하여 단 하나의 대상 엔티티만 매핑되는 경우'로 해석하기에 unique 제약조건을 추가합니다. 그리고 사실 이게 의미론적으로 더 맞습니다. 
- notification의 경우 하나의 알림에 대하여 하나의 소스 혹은 하나의 타깃과만 매핑되지 않습니다. 하나의 알림이 여러 개의 소스 또는 타깃과 매핑될 수 있죠 -> 따라서 manytoone이 의미적으로 더 적절합니다
- 따라서 manytoone으로 수정해줬습니다
- mysql의 on duplicate key의 경우 postgresql의 on conflict do update와 대응됩니다. 수정해줬습니다.
- 다만 on conflict do update의 경우 h2의 postgresql 호환 모드에서 지원되지 않습니다.
- 따라서 테스트에서는 RankingRepository를 모킹한 뒤 (다른 기능은 정상 …
> chore: PostgreSQL 마이그레이션
